plugins {
    id("io.micronaut.application") version "5.0.2"
}

// Feature 007. The system of record: it owns the billing data and it is the only place entitlements
// are enforced (FR-014, FR-023).
version = "0.1.0"
group = "dev.l4jlab.legacy"

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

micronaut {
    version = "5.1.5"
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(false)
        annotations("dev.l4jlab.legacy.*")
    }
}

dependencies {
    annotationProcessor("io.micronaut:micronaut-http-validation")
    annotationProcessor("io.micronaut.serde:micronaut-serde-processor")
    annotationProcessor("io.micronaut.data:micronaut-data-processor")
    annotationProcessor("io.micronaut.validation:micronaut-validation-processor")
    // Constitution: the OpenAPI description is generated by Micronaut OpenAPI from the Java types.
    // This service has an HTTP API, so it has one. The MCP server does not — see plan.md.
    annotationProcessor("io.micronaut.openapi:micronaut-openapi")

    implementation("io.micronaut:micronaut-http-server-netty")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    implementation("io.micronaut.validation:micronaut-validation")
    implementation("io.micronaut.data:micronaut-data-jdbc")
    implementation("io.micronaut.sql:micronaut-jdbc-hikari")
    implementation("io.micronaut.flyway:micronaut-flyway")
    implementation("io.micronaut:micronaut-management")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut.openapi:micronaut-openapi-annotations")
    implementation("jakarta.validation:jakarta.validation-api")
    // FR-015: this service verifies its own tokens; it shares no secret with the issuer.
    implementation("com.nimbusds:nimbus-jose-jwt")

    runtimeOnly("org.postgresql:postgresql")
    runtimeOnly("org.flywaydb:flyway-database-postgresql")
    runtimeOnly("ch.qos.logback:logback-classic")
    runtimeOnly("org.yaml:snakeyaml")

    testImplementation("io.micronaut.test:micronaut-test-junit5")
    testImplementation("io.micronaut:micronaut-http-client")
    testImplementation("org.assertj:assertj-core")
    testImplementation(platform("org.testcontainers:testcontainers-bom:2.0.5"))
    testImplementation("org.testcontainers:testcontainers")
    testImplementation("org.testcontainers:testcontainers-postgresql")
    testImplementation("org.testcontainers:testcontainers-junit-jupiter")
}

application {
    mainClass = "dev.l4jlab.legacy.Application"
}

tasks.withType<JavaCompile>().configureEach {
    options.release = 25
    options.compilerArgs.addAll(
        listOf(
            "-parameters",
            "-Amicronaut.processing.group=dev.l4jlab.legacy",
            // A fixed file name, for the same reason feature 003 fixed the backend's.
            "-Amicronaut.openapi.filename=openapi-legacy",
            "-Amicronaut.openapi.expand.api.version=${project.version}",
        ),
    )
}

tasks.named<Test>("test") {
    useJUnitPlatform()
    systemProperty("micronaut.environments", "test,test-capture")
}
