/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["catalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The history list, newest first.
         * @description The history list, newest first. Keyset paging, so a concurrent insert cannot skew a page.
         */
        get: operations["list"];
        put?: never;
        /**
         * Starts a run and returns immediately.
         * @description Starts a run and returns immediately. Two concurrent calls produce two independent runs.
         */
        post: operations["start"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description The companies and periods a learner may select. Backs the launcher's two dropdowns. */
        CatalogResponse: {
            companies: components["schemas"]["CatalogResponse.CompanyEntry"][];
        };
        "CatalogResponse.CompanyEntry": {
            companyId: string;
            companyName: string;
            periods: string[];
        };
        /** @description One indicator as the screen shows it. The value is a plain string, not a number, so the figure the learner reads is byte-identical to the figure that was computed and stored. Round-tripping through a JSON number would be the one place SC-005 could silently break. */
        IndicatorView: {
            name: string;
            value?: string | null;
            notApplicableReason?: string | null;
            derivedFrom: string[];
        };
        /** @description One node's record as the detail view shows it (US2). The four model fields are populated for position 4 only, and none of them, ever, carries the credential (FR-018). */
        NodeView: {
            /** Format: int32 */
            position: number;
            nodeName: string;
            succeeded: boolean;
            failureReason?: string | null;
            /** @description The boundary structure this node received, verbatim */
            inputPayload?: {
                [key: string]: unknown;
            } | null;
            /** @description The boundary structure this node produced, verbatim */
            outputPayload?: {
                [key: string]: unknown;
            } | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: int32 */
            durationMs: number;
            modelRequestText?: string | null;
            modelResponseText?: string | null;
            /** Format: int32 */
            inputTokens?: number | null;
            /** Format: int32 */
            outputTokens?: number | null;
        };
        /**
         * @description The full record of one run. Polled while the run is not terminal, then left alone.
         *
         *     `nodes` holds only the nodes that have started, in ascending position, so a running
         *     chain shows its progress. A failed run still returns the records of the nodes that completed
         *     (FR-015).
         */
        RunDetailResponse: {
            /** Format: uuid */
            runId: string;
            companyId: string;
            companyName?: string | null;
            period: string;
            status: string;
            currentNode?: string | null;
            failedNode?: string | null;
            failureReason?: string | null;
            providerMode: string;
            modelId: string;
            summary?: string | null;
            indicators?: components["schemas"]["IndicatorView"][] | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string | null;
            nodes: components["schemas"]["NodeView"][];
        };
        /** @description The history list, newest first (FR-014, US3). Carries no node payloads. */
        RunListResponse: {
            runs: components["schemas"]["RunListResponse.RunListEntry"][];
            nextCursor?: string | null;
        };
        "RunListResponse.RunListEntry": {
            /** Format: uuid */
            runId: string;
            companyId: string;
            companyName?: string | null;
            period: string;
            status: string;
            summaryPreview?: string | null;
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            endedAt?: string | null;
        };
        StartRunRequest: {
            companyId: string;
            period: string;
        };
        StartRunResponse: {
            /** Format: uuid */
            runId: string;
            status: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    catalog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description catalog 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description list 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunListResponse"];
                };
            };
        };
    };
    start: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description start 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunResponse"];
                };
            };
        };
    };
    detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description detail 200 response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunDetailResponse"];
                };
            };
        };
    };
}
